### ISSUE TITLE
Use Qt5

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/silab_online_monitor#3]
Switch to Qt5

**Comment by leloup314** [comment]
Need permission to push changes concerning Qt5 to online_monitor development, otherwise Travis still fails.

**Comment by DavidLP** [comment]
You are a developer of online_monitor and should be able to push code.

**Comment by leloup314** [comment]
Concerning online_monitor and silab_online_monitor now everything is switched to Qt5.
There are still two files in pyBAR using PyQt4 which are:
    **pybar/ViTablesPlugin/pybar_plugin.py
    pybar/online_monitor.py**
Build passes.

**Comment by leloup314** [comment]
As far as I see [this](https://github.com/SiLab-Bonn/pyBAR/blob/development/pybar/ViTablesPlugin/pybar_plugin.py#L10-L11) is the only place where we still use Qt4 in pyBAR development and master.
For online_monitors and silab_online_monitors development branch it's now Qt5
