### ISSUE TITLE
Merge or delete faster serialization branch

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/silab_online_monitor#4]
If the faster serialization does something better than the development it should be merged. Otherwise deleted.

**Comment by themperek** [comment]
It was much fater. One should generalize it. 
I can look for profiling test.

**Comment by themperek** [comment]
It was much fater. One should generalize it. 
I can look for profiling test.

**Comment by themperek** [comment]
It was much fater. One should generalize it. 
I can look for profiling test.

**Comment by themperek** [comment]
It was much fater. One should generalize it. 
I can look for profiling test.

**Comment by themperek** [comment]
It was much fater. One should generalize it. 
I can look for profiling test.

**Comment by DavidLP** [comment]
The serialization takes place in the [online_monitor](https://github.com/SiLab-Bonn/online_monitor) package. The faster serialization was implemented as an additional tool [here](https://github.com/SiLab-Bonn/online_monitor/blob/development/online_monitor/utils/utils.py#L190). The issue was (to my mind) that only numpy arrays were treated but other python objects did not work. But I also see that in the development [we already use](https://github.com/SiLab-Bonn/silab_online_monitor/blob/development/silab_online_monitor/converter/pybar_fei4.py#L59) the faster serialization. 
@leloup314 Please check if we need anything from the faster serialization branch, I guess it is already in development. Then delete.

**Comment by leloup314** [comment]
I think faster_serialization is already in development, but I don't know for sure now. Maybe one can directly see [here?](https://github.com/SiLab-Bonn/silab_online_monitor/networkl) Otherwise I'll check again

**Comment by DavidLP** [comment]
Your link is dead.

**Comment by leloup314** [comment]
[here](https://github.com/SiLab-Bonn/silab_online_monitor/network) . I asked Tomek and Toko and we already use faster serialization in development so I will delete the branch
